<?php

$title = 'Cadastrar um novo celular';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->basePath('celular/index/add'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('marca'));
echo $this->formRow($form->get('modelo'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();